Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,7 +1,10 @@
 image: docker:stable
 
 stages:
+  - setup 
   - publish
+  - deploy
+  - cleanup
 
 workflow:
   rules:
@@ -11,9 +14,52 @@ workflow:
 variables:
   TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
   TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
-  CI_VERSION: "1.0.${CI_PIPELINE_IID}"
+  CI_VERSION: "1.0.${CI_PIPELINE_ID}"
   IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_VERSION
 
+
+  COMMON_VAR: "This is a common variable"
+
+ 
+  KUBE_NAMESPACE: "greenpay"
+  HELM_RELEASE: "" #CHANGE NAME!!!!!!
+  SECRET_PATH: "" #CHANGE NAME!!!!!!
+  KUBE_CONTEXT: "your-kube-context"
+ # KUBECONFIG: "/path/to/kubeconfig"
+ #
+
+
+setup_registry_secret:
+  stage: setup
+  tags:
+    - deploy
+  script:
+    - echo "Setting up GitLab registry secret..."
+    - mkdir -p ~/.kube
+    - echo "$KUBECONFIG" > ~/.kube/config   # Load kubeconfig from GitLab CI/CD variable
+    - kubectl get nodes                     # Verify Kubernetes access
+    - |
+      if ! kubectl get ns $KUBE_NAMESPACE; then
+        echo "Creating namespace..."
+        kubectl create namespace $KUBE_NAMESPACE
+      else
+        echo "$KUBE_NAMESPACE namespace exists."
+      fi
+
+    - |
+      if ! kubectl get secret gitlab-registry-secret -n $KUBE_NAMESPACE; then
+        echo "Creating GitLab registry secret..."
+        kubectl create secret docker-registry gitlab-registry-secret \
+          --docker-server=$CI_REGISTRY \
+          --docker-username="gitlab+deploy-token-2" \
+          --docker-password=$GITLAB_REGISTRY_TOKEN \
+          --docker-email=someemail.example.com \
+          --namespace $KUBE_NAMESPACE
+      else
+        echo "GitLab registry secret already exists."
+      fi
+  only:
+    - development  # or your main branch
 
 publish:
   image: docker:latest
@@ -34,5 +80,47 @@ publish:
     - echo "$FINAL_IMAGE"
     - docker tag $IMAGE_TAG $FINAL_IMAGE
     - docker push $FINAL_IMAGE
+
   tags:
     - build
+  
+
+deploy:
+  stage: deploy
+  before_script:
+    - |
+      SECRET_PATH=$(grep "^$CI_PROJECT_ID," $CONFIG_SECRET_PATH | cut -d',' -f2 | tr -d ' ')
+      echo "Dynamic Variable: $SECRET_PATH"
+    - |
+      SERVICE_NAME=$(grep "^$CI_PROJECT_ID," $CONFIG_SERVICE_NAME | cut -d',' -f2 | tr -d ' ')
+      echo "Dynamic Variable: $SERVICE_NAME"
+    #- apt-get update && apt-get install -y git   # Install Git 
+    # Clone the Helm charts repository using the token
+    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.greentekpay.com/infra/helm/ms-chart.git helm-charts
+  script:
+    - helm upgrade --install "$SERVICE_NAME" "./helm-charts/java-charts/"   --namespace "$KUBE_NAMESPACE" --create-namespace --set serviceName=$SERVICE_NAME --set secretPath=$SECRET_PATH --set image.repository=$CI_REGISTRY_IMAGE --set image.tag=$CI_COMMIT_BRANCH-$CI_VERSION
+    - >
+      if ! kubectl rollout status deployment/$SERVICE_NAME --namespace $KUBE_NAMESPACE --timeout=60s; then
+        echo "Deployment rollout failed"
+        exit 1
+      fi
+  rules:
+    - if: $CI_COMMIT_BRANCH == "development"
+  tags:
+    - deploy
+    
+cleanup:
+  stage: cleanup
+  script:
+    - kubectl delete deployments.apps  $SERVICE_NAME -n  $KUBE_NAMESPACE --ignore-not-found=true
+    - kubectl delete service $SERVICE_NAME -n  $KUBE_NAMESPACE --ignore-not-found=true
+
+  when: manual
+  only:
+    - development
+  tags:
+    - deploy
+
+
+
+
